In [ ]:
# import tweepy
import tweepy as tw
# your Twitter API key and API secret
my_api_key = "vYnTjxjFWL471STe2HW2dERiN"
my_api_secret = "oTsvu8BI2rwxvzTge0xIreCTmcJJxxSESk7XINbQHvgsiibocG"
# authenticate
auth = tw.OAuthHandler(my_api_key, my_api_secret)
api = tw.API(auth, wait_on_rate_limit=True)

In [ ]:
# setting up a search query
search_query = "#airtel -filter:retweets"

In [ ]:
# get tweets from the API
tweets = tw.Cursor(api.search,
              q=search_query,
              lang="en",
              since="2019-01-01").items(500)
# store the API responses in a list
tweets_copy = []
for tweet in tweets:
    tweets_copy.append(tweet)
    
print("Total Tweets fetched:", len(tweets_copy))

Total Tweets fetched: 500

In [ ]:
import pandas as pd
# intialize the dataframe
tweets_df = pd.DataFrame()
# populate the dataframe
for tweet in tweets_copy:
    hashtags = []
    try:
        for hashtag in tweet.entities["hashtags"]:
            hashtags.append(hashtag["text"])
        text = api.get_status(id=tweet.id, tweet_mode='extended').full_text
    except:
        pass
    tweets_df = tweets_df.append(pd.DataFrame({'user_name': tweet.user.name, 
                                               'user_location': tweet.user.location,\
                                               'user_description': tweet.user.description,
                                               'user_verified': tweet.user.verified,
                                               'date': tweet.created_at,
                                               'text': text, 
                                               'hashtags': [hashtags if hashtags else None],
                                               'source': tweet.source}))
    tweets_df = tweets_df.reset_index(drop=True)
# show the dataframe
tweets_df.head()

,user_name,user_location,user_description,user_verified,date,text,hashtags,source
0,Aravindh S,"Tamil Nadu, India",Nemophilist ðŸŒŽ 90's KID ðŸ˜‰ ðŸ˜œ,False,2022-03-14 12:38:42,And I am hearing new stories that within a sma...,None,Twitter for iPhone
1,Gbest Bulk SMS,Abuja Nigeria,Providers of Bulk SMS | Data Bundle | Airtime ...,False,2022-03-14 12:21:29,Do U have excess Airtime in ur line and will l...,None,Twitter for Android
2,Kalyanashis Mahanty,"Barabhum , West Bengal, India",School teacher by profession and I am everythi...,False,2022-03-14 12:05:51,@airtelindia @Airtel_Presence bye bye for now....,None,Twitter for Android
3,"Network Palava - Free, Cheap Data Daily.","Lagos, Nigeria","Get Cheap, Free Browsing Solutions at https://...",False,2022-03-14 11:59:45,Working NapsternetV Configuration Files Downlo...,[mtn],Revive Social App
4,JayRoy ðŸ‡®ðŸ‡³,,Proud Indian \n\n(RT's r not endorsements),False,2022-03-14 11:55:01,@airtelnews @airtelindia @Airtel_Presence @air...,None,Twitter Web App

In [ ]:
tweets_df.shape

(500, 8)

In [ ]:
tweets_df

,user_name,user_location,user_description,user_verified,date,text,hashtags,source
0,Aravindh S,"Tamil Nadu, India",Nemophilist ðŸŒŽ 90's KID ðŸ˜‰ ðŸ˜œ,False,2022-03-14 12:38:42,And I am hearing new stories that within a sma...,None,Twitter for iPhone
1,Gbest Bulk SMS,Abuja Nigeria,Providers of Bulk SMS | Data Bundle | Airtime ...,False,2022-03-14 12:21:29,Do U have excess Airtime in ur line and will l...,None,Twitter for Android
2,Kalyanashis Mahanty,"Barabhum , West Bengal, India",School teacher by profession and I am everythi...,False,2022-03-14 12:05:51,@airtelindia @Airtel_Presence bye bye for now....,None,Twitter for Android
3,"Network Palava - Free, Cheap Data Daily.","Lagos, Nigeria","Get Cheap, Free Browsing Solutions at https://...",False,2022-03-14 11:59:45,Working NapsternetV Configuration Files Downlo...,[mtn],Revive Social App
4,JayRoy ðŸ‡®ðŸ‡³,,Proud Indian \n\n(RT's r not endorsements),False,2022-03-14 11:55:01,@airtelnews @airtelindia @Airtel_Presence @air...,None,Twitter Web App
...,...,...,...,...,...,...,...,...
495,Akshay Sood,Hoshiarpur,,False,2022-03-08 06:35:45,@Airtel_Presence @airtelindia My Airtel Xtrem...,None,Twitter Web App
496,The Rewind Guys,India,Tech News | Quick Thoughts | Comparisons | Bas...,False,2022-03-08 06:30:03,"Along with the credit card, both the companies...",None,Hootsuite Inc.
497,Telecom TALK,India,#Telecom #5G #Mobile #DTH\n \nPR Mails: news a...,True,2022-03-08 06:23:11,"Satcom: Jio, Airtel Entry Doesnâ€™t Mean Low Pri...","[Satcom, jio, Airtel]",Twitter Web App
498,Tarun Tyagi,"Ghaziabad, India","Author by Choice, Engineer by Profession and M...",False,2022-03-08 06:02:49,All #Airtel Internet Connections including Mob...,[Airtel],Twitter Web App
499,Developing Telecoms,London,Developing Telecoms is the international telec...,False,2022-03-08 06:00:03,"Bharti Airtel, Axis Bank announce strategic pa...","[India, BhartiAirtel, Airtel, ICT, CyberSecuri...",Developing Telecoms Auto Tweet

In [ ]:
tweets_df.to_csv(r'/content/drive/MyDrive/college/sem7/FYP/tweets_dataset.csv')